site_name: Oficina de Robótica

theme:
  name: material

  features:
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Alternar para o modo claro

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Alternar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Alternar para o modo automático

nav:
  - Home: index.md
  - Arduino UNO: arduino.md
  - Micro:bit : microbit.md
  - Raspbarry Pi: raspbarry.md

markdown_extensions:
- pymdownx.emoji
- pymdownx.highlight
- pymdownx.superfences