site_name: Oficina de Robótica

theme:
  name: material

  features:
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Modo claro

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Modo automático

nav:
  - Sobre: index.md
  - Nível básico: arduino.md
  - Nível intermediário: arduino.md
  - Nível avançado: arduino.md

markdown_extensions:
- pymdownx.emoji
- pymdownx.highlight
- pymdownx.superfences